### ISSUE TITLE
setDate function?

### ISSUE THREAD

**Issue by ticky** [calda/WatchKitTimePicker#2]
My use case involves updating the control’s displayed date based on a few factors, and I’m currently using the `setup(withInitiallySelectedDate:)` method, which works but has an overhead of having to repeat all the setup each time you update.

Would it be reasonable to either move the setup code to `init` and replace the current `setup` method with a `setDate`, or to add a `setDate` method which does just the date-setting stuff?

I’d be happy to put together a PR if either of these sound agreeable to you 😄

**Comment by calda** [comment]
That sounds like a sensible change. A PR would be great!

**Comment by calda** [comment]
More specifically, I’m on board with adding a `setDate` function.

**Comment by Reza-Rajabi** [comment]
Hi.
I work on this if it's OK.

**Comment by calda** [comment]
Sure, I’m happy to review a PR if you make one
